Add redis standard function and improve the handling of error
akiidjk/ProjectIppocrate pull request #2
Opened 2024-03-31 21:21 UTC by akiidjk

## Improvement at the code:

- Add model for the description of data
- Add simple function to communicate with redis
- Add an Error Manager for the handling of error in the code

2024-04-01 19:50 UTC, danmig06 requested changes
Looks alright, you also got rid of other boiler plate stuff we had missing, the redis GET/SET requests are easly generalizable though, just look at how many lines repeat in each of the 4 functions.

2024-04-01 20:07 UTC, danmig06 commented
What you could do is adding enum types for the type of request and, if you really want a separate _json function, making a macro that does the conversion and passes it the function along with the command SET

2024-04-02 06:36 UTC, akiidjk commented
OK so I try to generalise even more and repeat as little code as possible, I'll work on it this evening

2024-04-03 09:30 UTC, danmig06 approved these changes
this is more readable, consider using enum values for commands and making just one function called redis_send_command for example

2024-04-03 09:30 UTC, danmig06 commented on backend/src/redis.rs
> +// File with redis call
Make this code more D.R.Y. (read the comments)

2024-04-03 09:30 UTC, danmig06 commented on backend/src/error_manager.rs
> +use thiserror::Error;
This is nice

2024-04-03 09:30 UTC, danmig06 commented on backend/src/main.rs
>  mod data;
This will have to be changed in regards to the changes requested (read the comments)

2024-04-07 08:30 UTC, merged